### ISSUE TITLE
Pylint 

### ISSUE THREAD

**Issue by anthonye93** [Data-Linkage/dlh_utils#2]
we've got a whole lot of linting to do still #1

**Comment by digrks** [comment]
In addition to what we spoke about last week you should consider using black to edit tidy the existing code

**Comment by anthonye93** [comment]
Thanks Diogo, the pre commit hooks will be a lifesaver!

We tried automated linting with black, particularly for trailing whitespace, but it's so uncompromising it broke all module docstrings

**Comment by digrks** [comment]
Fair, worth noting that you can configure black to exclude certain formatting options https://black.readthedocs.io/en/stable/usage_and_configuration/the_basics.html#configuration-via-a-file

**Comment by hartj2** [comment]
Closing as linting has been done on separate pylint branch, and team has been shown how to pylint their own code before merging with main branch.
