### ISSUE TITLE
tests

### ISSUE THREAD

**Issue by anthonye93** [Data-Linkage/dlh_utils#5]
We need to update our tests and implement pytest, then building this into an automation workflow ran to check code integration on pushes to the master branch.

Existing tests needing tweaks (either due to function name changes, argument changes or output changes):

**dataframes:**
- test_concat (renamed args)
- test_dropColumns
- test_dropNulls
- test_literalColumn
- test_select (renamed args)
- test_cutOff

**linkage:**
- test_deterministic_linkage (this may be hard to test as this now writes out intermediate data)

**standardisation:**
- test_cutOff
- test_regReplace
- test_removePunct
- test_standardise_date (renamed args)
- test_add_leading_zeros (commented out code, need to make sure this works)
- 
new functions that need tests:

**linkage:**
- metaphone
- alpha_name
- soundex
- std_lev_score
- jaro
- jaro_winkler
- blocking
- cluster_number

all functions in profiling, sessions and utilities

**Comment by hartj2** [comment]
Closing - outdated and keeping track of missing tests on Trello
